# Generated by Django 2.2.3 on 2019-07-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.EmailField(default='fedor_coder@mail.ru', max_length=254, verbose_name='Email'),
        ),
    ]
