# Generated by Django 2.2.3 on 2019-07-03 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ad',
        ),
    ]
