# Generated by Django 2.2.3 on 2019-07-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularday',
            name='day',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='populartime',
            name='time',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='popularday',
            unique_together={('task', 'day')},
        ),
        migrations.AlterUniqueTogether(
            name='populartime',
            unique_together={('task', 'time')},
        ),
    ]
